sudo: false
services:
  - redis-server
  - memcached
  - mongodb
  - couchdb
  - elasticsearch

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7.9"

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch
